image: Ubuntu  # образ для сборки

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x gradlew
  - java -jar ./artifacts/app-card-delivery.jar &

build_script:
  - ./gradlew test "-Dselenide.headless=true"